
/** \page keycodes Annchienta keyCodes.
 *
 *
 *  \li SDLK_UNKNOWN
 *  \li SDLK_FIRST
 *  \li SDLK_BACKSPACE
 *  \li SDLK_TAB
 *  \li SDLK_CLEAR
 *  \li SDLK_RETURN
 *  \li SDLK_PAUSE
 *  \li SDLK_ESCAPE
 *  \li SDLK_SPACE
 *  \li SDLK_EXCLAIM
 *  \li SDLK_QUOTEDBL
 *  \li SDLK_HASH
 *  \li SDLK_DOLLAR
 *  \li SDLK_AMPERSAND
 *  \li SDLK_QUOTE
 *  \li SDLK_LEFTPAREN
 *  \li SDLK_RIGHTPAREN
 *  \li SDLK_ASTERISK
 *  \li SDLK_PLUS
 *  \li SDLK_COMMA
 *  \li SDLK_MINUS
 *  \li SDLK_PERIOD
 *  \li SDLK_SLASH
 *  \li SDLK_0
 *  \li SDLK_1
 *  \li SDLK_2
 *  \li SDLK_3
 *  \li SDLK_4
 *  \li SDLK_5
 *  \li SDLK_6
 *  \li SDLK_7
 *  \li SDLK_8
 *  \li SDLK_9
 *  \li SDLK_COLON
 *  \li SDLK_SEMICOLON
 *  \li SDLK_LESS
 *  \li SDLK_EQUALS
 *  \li SDLK_GREATER
 *  \li SDLK_QUESTION
 *  \li SDLK_AT
 *  \li SDLK_LEFTBRACKET
 *  \li SDLK_BACKSLASH
 *  \li SDLK_RIGHTBRACKET
 *  \li SDLK_CARET
 *  \li SDLK_UNDERSCORE
 *  \li SDLK_BACKQUOTE
 *  \li SDLK_a
 *  \li SDLK_b
 *  \li SDLK_c
 *  \li SDLK_d
 *  \li SDLK_e
 *  \li SDLK_f
 *  \li SDLK_g
 *  \li SDLK_h
 *  \li SDLK_i
 *  \li SDLK_j
 *  \li SDLK_k
 *  \li SDLK_l
 *  \li SDLK_m
 *  \li SDLK_n
 *  \li SDLK_o
 *  \li SDLK_p
 *  \li SDLK_q
 *  \li SDLK_r
 *  \li SDLK_s
 *  \li SDLK_t
 *  \li SDLK_u
 *  \li SDLK_v
 *  \li SDLK_w
 *  \li SDLK_x
 *  \li SDLK_y
 *  \li SDLK_z
 *  \li SDLK_DELETE
 *  \li SDLK_WORLD_0
 *  \li SDLK_WORLD_1
 *  \li SDLK_WORLD_2
 *  \li SDLK_WORLD_3
 *  \li SDLK_WORLD_4
 *  \li SDLK_WORLD_5
 *  \li SDLK_WORLD_6
 *  \li SDLK_WORLD_7
 *  \li SDLK_WORLD_8
 *  \li SDLK_WORLD_9
 *  \li SDLK_WORLD_10
 *  \li SDLK_WORLD_11
 *  \li SDLK_WORLD_12
 *  \li SDLK_WORLD_13
 *  \li SDLK_WORLD_14
 *  \li SDLK_WORLD_15
 *  \li SDLK_WORLD_16
 *  \li SDLK_WORLD_17
 *  \li SDLK_WORLD_18
 *  \li SDLK_WORLD_19
 *  \li SDLK_WORLD_20
 *  \li SDLK_WORLD_21
 *  \li SDLK_WORLD_22
 *  \li SDLK_WORLD_23
 *  \li SDLK_WORLD_24
 *  \li SDLK_WORLD_25
 *  \li SDLK_WORLD_26
 *  \li SDLK_WORLD_27
 *  \li SDLK_WORLD_28
 *  \li SDLK_WORLD_29
 *  \li SDLK_WORLD_30
 *  \li SDLK_WORLD_31
 *  \li SDLK_WORLD_32
 *  \li SDLK_WORLD_33
 *  \li SDLK_WORLD_34
 *  \li SDLK_WORLD_35
 *  \li SDLK_WORLD_36
 *  \li SDLK_WORLD_37
 *  \li SDLK_WORLD_38
 *  \li SDLK_WORLD_39
 *  \li SDLK_WORLD_40
 *  \li SDLK_WORLD_41
 *  \li SDLK_WORLD_42
 *  \li SDLK_WORLD_43
 *  \li SDLK_WORLD_44
 *  \li SDLK_WORLD_45
 *  \li SDLK_WORLD_46
 *  \li SDLK_WORLD_47
 *  \li SDLK_WORLD_48
 *  \li SDLK_WORLD_49
 *  \li SDLK_WORLD_50
 *  \li SDLK_WORLD_51
 *  \li SDLK_WORLD_52
 *  \li SDLK_WORLD_53
 *  \li SDLK_WORLD_54
 *  \li SDLK_WORLD_55
 *  \li SDLK_WORLD_56
 *  \li SDLK_WORLD_57
 *  \li SDLK_WORLD_58
 *  \li SDLK_WORLD_59
 *  \li SDLK_WORLD_60
 *  \li SDLK_WORLD_61
 *  \li SDLK_WORLD_62
 *  \li SDLK_WORLD_63
 *  \li SDLK_WORLD_64
 *  \li SDLK_WORLD_65
 *  \li SDLK_WORLD_66
 *  \li SDLK_WORLD_67
 *  \li SDLK_WORLD_68
 *  \li SDLK_WORLD_69
 *  \li SDLK_WORLD_70
 *  \li SDLK_WORLD_71
 *  \li SDLK_WORLD_72
 *  \li SDLK_WORLD_73
 *  \li SDLK_WORLD_74
 *  \li SDLK_WORLD_75
 *  \li SDLK_WORLD_76
 *  \li SDLK_WORLD_77
 *  \li SDLK_WORLD_78
 *  \li SDLK_WORLD_79
 *  \li SDLK_WORLD_80
 *  \li SDLK_WORLD_81
 *  \li SDLK_WORLD_82
 *  \li SDLK_WORLD_83
 *  \li SDLK_WORLD_84
 *  \li SDLK_WORLD_85
 *  \li SDLK_WORLD_86
 *  \li SDLK_WORLD_87
 *  \li SDLK_WORLD_88
 *  \li SDLK_WORLD_89
 *  \li SDLK_WORLD_90
 *  \li SDLK_WORLD_91
 *  \li SDLK_WORLD_92
 *  \li SDLK_WORLD_93
 *  \li SDLK_WORLD_94
 *  \li SDLK_WORLD_95
 *  \li SDLK_KP0
 *  \li SDLK_KP1
 *  \li SDLK_KP2
 *  \li SDLK_KP3
 *  \li SDLK_KP4
 *  \li SDLK_KP5
 *  \li SDLK_KP6
 *  \li SDLK_KP7
 *  \li SDLK_KP8
 *  \li SDLK_KP9
 *  \li SDLK_KP_PERIOD
 *  \li SDLK_KP_DIVIDE
 *  \li SDLK_KP_MULTIPLY
 *  \li SDLK_KP_MINUS
 *  \li SDLK_KP_PLUS
 *  \li SDLK_KP_ENTER
 *  \li SDLK_KP_EQUALS
 *  \li SDLK_UP
 *  \li SDLK_DOWN
 *  \li SDLK_RIGHT
 *  \li SDLK_LEFT
 *  \li SDLK_INSERT
 *  \li SDLK_HOME
 *  \li SDLK_END
 *  \li SDLK_PAGEUP
 *  \li SDLK_PAGEDOWN
 *  \li SDLK_F1
 *  \li SDLK_F2
 *  \li SDLK_F3
 *  \li SDLK_F4
 *  \li SDLK_F5
 *  \li SDLK_F6
 *  \li SDLK_F7
 *  \li SDLK_F8
 *  \li SDLK_F9
 *  \li SDLK_F10
 *  \li SDLK_F11
 *  \li SDLK_F12
 *  \li SDLK_F13
 *  \li SDLK_F14
 *  \li SDLK_F15
 *  \li SDLK_NUMLOCK
 *  \li SDLK_CAPSLOCK
 *  \li SDLK_SCROLLOCK
 *  \li SDLK_RSHIFT
 *  \li SDLK_LSHIFT
 *  \li SDLK_RCTRL
 *  \li SDLK_LCTRL
 *  \li SDLK_RALT
 *  \li SDLK_LALT
 *  \li SDLK_RMETA
 *  \li SDLK_LMETA
 *  \li SDLK_LSUPER
 *  \li SDLK_RSUPER
 *  \li SDLK_MODE
 *  \li SDLK_COMPOSE
 *  \li SDLK_HELP
 *  \li SDLK_PRINT
 *  \li SDLK_SYSREQ
 *  \li SDLK_BREAK
 *  \li SDLK_MENU
 *  \li SDLK_POWER
 *  \li SDLK_EURO
 *  \li SDLK_UNDO
 *  \li SDLK_LAST
 *  \li KMOD_NONE
 *  \li KMOD_LSHIFT
 *  \li KMOD_RSHIFT
 *  \li KMOD_LCTRL
 *  \li KMOD_RCTRL
 *  \li KMOD_LALT
 *  \li KMOD_RALT
 *  \li KMOD_LMETA
 *  \li KMOD_RMETA
 *  \li KMOD_NUM
 *  \li KMOD_CAPS
 *  \li KMOD_MODE
 *  \li KMOD_RESERVED
 */
