
## \page keycodes Annchienta keyCodes.
#
#
#  \li annchienta.SDLK_UNKNOWN
#  \li annchienta.SDLK_FIRST
#  \li annchienta.SDLK_BACKSPACE
#  \li annchienta.SDLK_TAB
#  \li annchienta.SDLK_CLEAR
#  \li annchienta.SDLK_RETURN
#  \li annchienta.SDLK_PAUSE
#  \li annchienta.SDLK_ESCAPE
#  \li annchienta.SDLK_SPACE
#  \li annchienta.SDLK_EXCLAIM
#  \li annchienta.SDLK_QUOTEDBL
#  \li annchienta.SDLK_HASH
#  \li annchienta.SDLK_DOLLAR
#  \li annchienta.SDLK_AMPERSAND
#  \li annchienta.SDLK_QUOTE
#  \li annchienta.SDLK_LEFTPAREN
#  \li annchienta.SDLK_RIGHTPAREN
#  \li annchienta.SDLK_ASTERISK
#  \li annchienta.SDLK_PLUS
#  \li annchienta.SDLK_COMMA
#  \li annchienta.SDLK_MINUS
#  \li annchienta.SDLK_PERIOD
#  \li annchienta.SDLK_SLASH
#  \li annchienta.SDLK_0
#  \li annchienta.SDLK_1
#  \li annchienta.SDLK_2
#  \li annchienta.SDLK_3
#  \li annchienta.SDLK_4
#  \li annchienta.SDLK_5
#  \li annchienta.SDLK_6
#  \li annchienta.SDLK_7
#  \li annchienta.SDLK_8
#  \li annchienta.SDLK_9
#  \li annchienta.SDLK_COLON
#  \li annchienta.SDLK_SEMICOLON
#  \li annchienta.SDLK_LESS
#  \li annchienta.SDLK_EQUALS
#  \li annchienta.SDLK_GREATER
#  \li annchienta.SDLK_QUESTION
#  \li annchienta.SDLK_AT
#  \li annchienta.SDLK_LEFTBRACKET
#  \li annchienta.SDLK_BACKSLASH
#  \li annchienta.SDLK_RIGHTBRACKET
#  \li annchienta.SDLK_CARET
#  \li annchienta.SDLK_UNDERSCORE
#  \li annchienta.SDLK_BACKQUOTE
#  \li annchienta.SDLK_a
#  \li annchienta.SDLK_b
#  \li annchienta.SDLK_c
#  \li annchienta.SDLK_d
#  \li annchienta.SDLK_e
#  \li annchienta.SDLK_f
#  \li annchienta.SDLK_g
#  \li annchienta.SDLK_h
#  \li annchienta.SDLK_i
#  \li annchienta.SDLK_j
#  \li annchienta.SDLK_k
#  \li annchienta.SDLK_l
#  \li annchienta.SDLK_m
#  \li annchienta.SDLK_n
#  \li annchienta.SDLK_o
#  \li annchienta.SDLK_p
#  \li annchienta.SDLK_q
#  \li annchienta.SDLK_r
#  \li annchienta.SDLK_s
#  \li annchienta.SDLK_t
#  \li annchienta.SDLK_u
#  \li annchienta.SDLK_v
#  \li annchienta.SDLK_w
#  \li annchienta.SDLK_x
#  \li annchienta.SDLK_y
#  \li annchienta.SDLK_z
#  \li annchienta.SDLK_DELETE
#  \li annchienta.SDLK_WORLD_0
#  \li annchienta.SDLK_WORLD_1
#  \li annchienta.SDLK_WORLD_2
#  \li annchienta.SDLK_WORLD_3
#  \li annchienta.SDLK_WORLD_4
#  \li annchienta.SDLK_WORLD_5
#  \li annchienta.SDLK_WORLD_6
#  \li annchienta.SDLK_WORLD_7
#  \li annchienta.SDLK_WORLD_8
#  \li annchienta.SDLK_WORLD_9
#  \li annchienta.SDLK_WORLD_10
#  \li annchienta.SDLK_WORLD_11
#  \li annchienta.SDLK_WORLD_12
#  \li annchienta.SDLK_WORLD_13
#  \li annchienta.SDLK_WORLD_14
#  \li annchienta.SDLK_WORLD_15
#  \li annchienta.SDLK_WORLD_16
#  \li annchienta.SDLK_WORLD_17
#  \li annchienta.SDLK_WORLD_18
#  \li annchienta.SDLK_WORLD_19
#  \li annchienta.SDLK_WORLD_20
#  \li annchienta.SDLK_WORLD_21
#  \li annchienta.SDLK_WORLD_22
#  \li annchienta.SDLK_WORLD_23
#  \li annchienta.SDLK_WORLD_24
#  \li annchienta.SDLK_WORLD_25
#  \li annchienta.SDLK_WORLD_26
#  \li annchienta.SDLK_WORLD_27
#  \li annchienta.SDLK_WORLD_28
#  \li annchienta.SDLK_WORLD_29
#  \li annchienta.SDLK_WORLD_30
#  \li annchienta.SDLK_WORLD_31
#  \li annchienta.SDLK_WORLD_32
#  \li annchienta.SDLK_WORLD_33
#  \li annchienta.SDLK_WORLD_34
#  \li annchienta.SDLK_WORLD_35
#  \li annchienta.SDLK_WORLD_36
#  \li annchienta.SDLK_WORLD_37
#  \li annchienta.SDLK_WORLD_38
#  \li annchienta.SDLK_WORLD_39
#  \li annchienta.SDLK_WORLD_40
#  \li annchienta.SDLK_WORLD_41
#  \li annchienta.SDLK_WORLD_42
#  \li annchienta.SDLK_WORLD_43
#  \li annchienta.SDLK_WORLD_44
#  \li annchienta.SDLK_WORLD_45
#  \li annchienta.SDLK_WORLD_46
#  \li annchienta.SDLK_WORLD_47
#  \li annchienta.SDLK_WORLD_48
#  \li annchienta.SDLK_WORLD_49
#  \li annchienta.SDLK_WORLD_50
#  \li annchienta.SDLK_WORLD_51
#  \li annchienta.SDLK_WORLD_52
#  \li annchienta.SDLK_WORLD_53
#  \li annchienta.SDLK_WORLD_54
#  \li annchienta.SDLK_WORLD_55
#  \li annchienta.SDLK_WORLD_56
#  \li annchienta.SDLK_WORLD_57
#  \li annchienta.SDLK_WORLD_58
#  \li annchienta.SDLK_WORLD_59
#  \li annchienta.SDLK_WORLD_60
#  \li annchienta.SDLK_WORLD_61
#  \li annchienta.SDLK_WORLD_62
#  \li annchienta.SDLK_WORLD_63
#  \li annchienta.SDLK_WORLD_64
#  \li annchienta.SDLK_WORLD_65
#  \li annchienta.SDLK_WORLD_66
#  \li annchienta.SDLK_WORLD_67
#  \li annchienta.SDLK_WORLD_68
#  \li annchienta.SDLK_WORLD_69
#  \li annchienta.SDLK_WORLD_70
#  \li annchienta.SDLK_WORLD_71
#  \li annchienta.SDLK_WORLD_72
#  \li annchienta.SDLK_WORLD_73
#  \li annchienta.SDLK_WORLD_74
#  \li annchienta.SDLK_WORLD_75
#  \li annchienta.SDLK_WORLD_76
#  \li annchienta.SDLK_WORLD_77
#  \li annchienta.SDLK_WORLD_78
#  \li annchienta.SDLK_WORLD_79
#  \li annchienta.SDLK_WORLD_80
#  \li annchienta.SDLK_WORLD_81
#  \li annchienta.SDLK_WORLD_82
#  \li annchienta.SDLK_WORLD_83
#  \li annchienta.SDLK_WORLD_84
#  \li annchienta.SDLK_WORLD_85
#  \li annchienta.SDLK_WORLD_86
#  \li annchienta.SDLK_WORLD_87
#  \li annchienta.SDLK_WORLD_88
#  \li annchienta.SDLK_WORLD_89
#  \li annchienta.SDLK_WORLD_90
#  \li annchienta.SDLK_WORLD_91
#  \li annchienta.SDLK_WORLD_92
#  \li annchienta.SDLK_WORLD_93
#  \li annchienta.SDLK_WORLD_94
#  \li annchienta.SDLK_WORLD_95
#  \li annchienta.SDLK_KP0
#  \li annchienta.SDLK_KP1
#  \li annchienta.SDLK_KP2
#  \li annchienta.SDLK_KP3
#  \li annchienta.SDLK_KP4
#  \li annchienta.SDLK_KP5
#  \li annchienta.SDLK_KP6
#  \li annchienta.SDLK_KP7
#  \li annchienta.SDLK_KP8
#  \li annchienta.SDLK_KP9
#  \li annchienta.SDLK_KP_PERIOD
#  \li annchienta.SDLK_KP_DIVIDE
#  \li annchienta.SDLK_KP_MULTIPLY
#  \li annchienta.SDLK_KP_MINUS
#  \li annchienta.SDLK_KP_PLUS
#  \li annchienta.SDLK_KP_ENTER
#  \li annchienta.SDLK_KP_EQUALS
#  \li annchienta.SDLK_UP
#  \li annchienta.SDLK_DOWN
#  \li annchienta.SDLK_RIGHT
#  \li annchienta.SDLK_LEFT
#  \li annchienta.SDLK_INSERT
#  \li annchienta.SDLK_HOME
#  \li annchienta.SDLK_END
#  \li annchienta.SDLK_PAGEUP
#  \li annchienta.SDLK_PAGEDOWN
#  \li annchienta.SDLK_F1
#  \li annchienta.SDLK_F2
#  \li annchienta.SDLK_F3
#  \li annchienta.SDLK_F4
#  \li annchienta.SDLK_F5
#  \li annchienta.SDLK_F6
#  \li annchienta.SDLK_F7
#  \li annchienta.SDLK_F8
#  \li annchienta.SDLK_F9
#  \li annchienta.SDLK_F10
#  \li annchienta.SDLK_F11
#  \li annchienta.SDLK_F12
#  \li annchienta.SDLK_F13
#  \li annchienta.SDLK_F14
#  \li annchienta.SDLK_F15
#  \li annchienta.SDLK_NUMLOCK
#  \li annchienta.SDLK_CAPSLOCK
#  \li annchienta.SDLK_SCROLLOCK
#  \li annchienta.SDLK_RSHIFT
#  \li annchienta.SDLK_LSHIFT
#  \li annchienta.SDLK_RCTRL
#  \li annchienta.SDLK_LCTRL
#  \li annchienta.SDLK_RALT
#  \li annchienta.SDLK_LALT
#  \li annchienta.SDLK_RMETA
#  \li annchienta.SDLK_LMETA
#  \li annchienta.SDLK_LSUPER
#  \li annchienta.SDLK_RSUPER
#  \li annchienta.SDLK_MODE
#  \li annchienta.SDLK_COMPOSE
#  \li annchienta.SDLK_HELP
#  \li annchienta.SDLK_PRINT
#  \li annchienta.SDLK_SYSREQ
#  \li annchienta.SDLK_BREAK
#  \li annchienta.SDLK_MENU
#  \li annchienta.SDLK_POWER
#  \li annchienta.SDLK_EURO
#  \li annchienta.SDLK_UNDO
#  \li annchienta.SDLK_LAST
#  \li annchienta.KMOD_NONE
#  \li annchienta.KMOD_LSHIFT
#  \li annchienta.KMOD_RSHIFT
#  \li annchienta.KMOD_LCTRL
#  \li annchienta.KMOD_RCTRL
#  \li annchienta.KMOD_LALT
#  \li annchienta.KMOD_RALT
#  \li annchienta.KMOD_LMETA
#  \li annchienta.KMOD_RMETA
#  \li annchienta.KMOD_NUM
#  \li annchienta.KMOD_CAPS
#  \li annchienta.KMOD_MODE
#  \li annchienta.KMOD_RESERVED

